apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-pipeline-run
spec:
  pipelineRef:
    name: build-and-push-pipeline
  serviceAccountName: default
  resources:
    - name: git-source
      resourceSpec:
        type: git
        params:
          - name: url
            value: "https://github.com/mooazsayyed/devops_Assignment.git"
  params:
    - name: gitrepo
      value:
        url: "https://github.com/mooazsayyed/devops_Assignment.git"
    - name: context-dir
      value: "."
    - name: dockerfile
      value: "./Dockerfile"
    - name: docker-image
      value: "mooaz/devops-assignment:latest"
  secrets:
    - name: regcred